server:
  port: 8082

spring:
  application:
    name: notification-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0  # 100% requestów — do nauki, na produkcji 0.1
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

otel:
  exporter:
    otlp:
      endpoint: http://tempo:4317
      protocol: grpc
  resource:
    attributes:
      service.name: notification-service
  logs:
    exporter: none
  metrics:
    exporter: none
  instrumentation:
    spring-webmvc:
      enabled: false
    spring-web:
      enabled: false

notification:
  queue:
    max-size: 100
  batch:
    size: 10
    interval-ms: 5000

logging:
  level:
    com.demo: INFO
